# -*- coding: utf-8 -*-
"""Recession_Forecasting_ML_Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KgQhu-aAZnkWGOwH4Voqw2BMaqcAmJue

# Machine Learning to Forecast Recessions
This notebook implements a complete pipeline for forecasting economic recessions using machine learning.
It includes data preprocessing, feature engineering, model training, evaluation, and interpretability.
Author: *Your Name Here*
Date: *Add Date Here*
"""

# Install required packages (for Google Colab)
!pip install scikit-learn xgboost imbalanced-learn shap

# Import libraries
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score
import xgboost as xgb
from imblearn.over_sampling import SMOTE
import shap
import matplotlib.pyplot as plt
import seaborn as sns

"""## Load and Preprocess Data
We will load the cleaned CSV file and proceed with feature engineering.
"""

# Load cleaned data
df = pd.read_csv("/content/Cleaned_Data_for_ML_Project.csv")
df.columns = ['Year', 'GDP Growth Rate (Annual)', 'Industrial Production Index', 'Unemployment Rate', 'CPI Annual', 'Yield Spread (10-year Treasury - Federal Funds Rate)', 'NBER Recession Indicators']
df['Year'] = pd.to_numeric(df['Year'], errors='coerce')
df['GDP Growth Rate (Annual)'] = pd.to_numeric(df['GDP Growth Rate (Annual)'], errors='coerce')
df['Industrial Production Index'] = pd.to_numeric(df['Industrial Production Index'], errors='coerce')
df['Unemployment Rate'] = pd.to_numeric(df['Unemployment Rate'], errors='coerce')
df['CPI Annual'] = pd.to_numeric(df['CPI Annual'], errors='coerce')
df['Yield Spread (10-year Treasury - Federal Funds Rate)'] = pd.to_numeric(df['Yield Spread (10-year Treasury - Federal Funds Rate)'], errors='coerce')
df['NBER Recession Indicators'] = pd.to_numeric(df['NBER Recession Indicators'], errors='coerce')
df.dropna(inplace=True)
df.head()

"""## Feature Engineering
We will create lagged features and normalize the data.
"""

# Create lagged features
lags = [1, 2, 4]
for col in df.columns:
    if col != 'NBER Recession Indicators' and col != 'Year':
        for lag in lags:
            df[f'{col}_lag{lag}'] = df[col].shift(lag)
df.dropna(inplace=True)

# Normalize features
X = df.drop(columns=['NBER Recession Indicators', 'Year'])
y = df['NBER Recession Indicators']
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_scaled[:5]  # Show first 5 rows of scaled features

"""## Train-Test Split and SMOTE
We will split the data and handle class imbalance using SMOTE.
"""

# Stratified train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42, stratify=y
)

# Train-test split with stratification
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42, stratify=y)

# Apply SMOTE only to the training data
sm = SMOTE(random_state=42, k_neighbors=min(5, sum(y_train == 1) - 1))
X_train_resampled, y_train_resampled = sm.fit_resample(X_train, y_train)

"""## Train Models
We will train Logistic Regression, Random Forest, and XGBoost models.
"""

# Logistic Regression
log_model = LogisticRegression(max_iter=1000)
log_model.fit(X_train_resampled, y_train_resampled)

# Random Forest
rf_model = RandomForestClassifier(n_estimators=100, max_depth=6)
rf_model.fit(X_train_resampled, y_train_resampled)

# XGBoost
xgb_model = xgb.XGBClassifier(n_estimators=200, learning_rate=0.05, max_depth=6)
xgb_model.fit(X_train_resampled, y_train_resampled)

"""## Evaluate Models
We will evaluate models using precision, recall, AUC, and confusion matrix.
"""

def evaluate(model, X_test, y_test):
    y_pred = model.predict(X_test)
    print(confusion_matrix(y_test, y_pred))
    print(classification_report(y_test, y_pred))
    print("AUC:", roc_auc_score(y_test, model.predict_proba(X_test)[:, 1]))

evaluate(rf_model, X_test, y_test)

"""## Feature Importance (Random Forest)"""

importances = rf_model.feature_importances_
features = X.columns
sns.barplot(x=importances, y=features)
plt.title("Feature Importance")
plt.show()

"""## SHAP Values for XGBoost"""

explainer = shap.Explainer(xgb_model)
shap_values = explainer(X_test)
shap.summary_plot(shap_values, X_test)